name: merged-pr-labels
description: Get labels of Pull Request associated with the commit that triggered your workflow. Easy way to automate processes by using pull request labels
author: kiprasmel

branding:
  icon: heart
  color: red

inputs:
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  labels:
    description: JSON-stringified array of labels, that were present in the PR

runs:
  using: node20
  main: dist/index.js
