name: merged-pr-labels
description: Automate processes with pull request labels. Get labels of PR associated with the commit that triggered your workflow.
author: kiprasmel

branding:
  icon: heart
  color: red

inputs:
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  labels:
    description: JSON-stringified array of labels, that were present in the PR

runs:
  using: node20
  main: dist/index.js
